version: "3"
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
    dj:
        build: .
        ports:
            - 80:8000
        volumes:
            - .:/app
        stdin_open: true
        tty: true
        command: bash
        depends_on: 
            - db